### ISSUE TITLE
Cloned posts are not visible in the admin

### ISSUE THREAD

**Issue by pdewouters** [humanmade/post-cloner#27]
After cloning a post on an Altis site, I expect to see it listed in the admin. However notice in the screenshot below. there should be 4 drafts, but none are visible

<img width="367" alt="Screenshot 2020-07-30 at 11 49 57" src="https://user-images.githubusercontent.com/30460/88914665-daebd680-d25a-11ea-8541-7ac952f88012.png">

**Comment by roborourke** [comment]
Can you double check that the search module is up to date? It might be related to a regression there that was fixed recently. If they still don't show try running `composer server cli -- elasticpress index --setup --network-wide` and let us know if they show up after that.

**Comment by pdewouters** [comment]
oh I was just debugging this actually, it is not related to this plugin, but as you say, it's related to enhanced search
